# Generated by Django 4.0.1 on 2022-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pkid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
